Citizen.CreateThread(function()
	AddTextEntry("ACTIP", "Acter Industrial Park")
	AddTextEntry("ACTRR", "Acter")
	AddTextEntry("ALDCI", "Alderney City")
	AddTextEntry("ALSCF", "Alderney State Correctional Facility")
	AddTextEntry("BEECW", "Beechwood City")
	AddTextEntry("BEGGA", "Beachgate")
	AddTextEntry("BERCH", "Berchem")
	AddTextEntry("BOAB", "BOABO")
	AddTextEntry("BOTU", "Booth Tunnel")
	AddTextEntry("BOULE", "Boulevard")
	AddTextEntry("BRALG", "Algonquin Bridge")
	AddTextEntry("BRBRO", "Broker Bridge")
	AddTextEntry("BRDBB", "Dukes Bay Bridge")
	AddTextEntry("BREBB", "East Borough Bridge")
	AddTextEntry("CASGC", "Castle Garden City")
	AddTextEntry("CASGR", "Castle Gardens")
	AddTextEntry("CERHE", "Cerveza Heights")
	AddTextEntry("CHAPO", "Chase Point")
	AddTextEntry("CHISL", "Charge Island")
	AddTextEntry("CHITO", "Chinatown")
	AddTextEntry("CITH", "City Hall")
	AddTextEntry("COISL", "Colony Island")
	AddTextEntry("DOWTW", "Downtown")
	AddTextEntry("EAHOL", "East Holland")
	AddTextEntry("EASON", "Easton")
	AddTextEntry("EISLC", "East Island City")
	AddTextEntry("ESHOO", "East Hook")
	AddTextEntry("FIISL", "Firefly Island")
	AddTextEntry("FIREP", "Firefly Projects")
	AddTextEntry("FISSN", "Fishmarket North")
	AddTextEntry("FISSO", "Fishmarket South")
	AddTextEntry("FORSI", "Fortside")
	AddTextEntry("FRANI", "Francis International Airport")
	AddTextEntry("HAPIN", "Happiness Island")
	AddTextEntry("HATGA", "Hatton Gardens")
	AddTextEntry("HIBRG", "Hickey Bridge")
	AddTextEntry("HOBEH", "Hove Beach")
	AddTextEntry("INSTI", "Industrial")
	AddTextEntry("LANCA", "Lancaster")
	AddTextEntry("LANCE", "Lancet")
	AddTextEntry("LEAPE", "Leaper's Bridge")
	AddTextEntry("LEFWO", "Leftwood")
	AddTextEntry("LITAL", "Little Italy")
	AddTextEntry("LOWEA", "Lower Easton")
	AddTextEntry("LTBAY", "Little Bay")
	AddTextEntry("MEADH", "Meadow Hills")
	AddTextEntry("MEADP", "Meadows Park")
	AddTextEntry("MIDPA", "Middle Park")
	AddTextEntry("MIDPE", "Middle Park East")
	AddTextEntry("MIDPW", "Middle Park West")
	AddTextEntry("NOHOL", "North Holland")
	AddTextEntry("NORMY", "Normandy")
	AddTextEntry("NORWO", "Northwood")
	AddTextEntry("NOWOB", "Northwood Heights Bridge")
	AddTextEntry("NRTGA", "Northern Gardens")
	AddTextEntry("OUTL", "Outlook")
	AddTextEntry("PORTU", "Port Tudor")
	AddTextEntry("PUGAT", "Purgatory")
	AddTextEntry("ROTTH", "Rotterdam Hill")
	AddTextEntry("SCHOL", "Schottler")
	AddTextEntry("STARJ", "Star Junction")
	AddTextEntry("STEIN", "Steinway")
	AddTextEntry("STHBO", "South Bohan")
	AddTextEntry("SUFFO", "Suffolk")
	AddTextEntry("SUTHS", "South Slopes")
	AddTextEntry("THPRES", "Presidents City")
	AddTextEntry("THTRI", "The Triangle")
	AddTextEntry("THXCH", "The Exchange")
	AddTextEntry("TMEQU", "The Meat Quarter")
	AddTextEntry("TUDOR", "Tudor")
	AddTextEntry("VASIH", "Varsity Heights")
	AddTextEntry("WESDY", "Westdyke")
	AddTextEntry("WESMI", "Westminster")
	AddTextEntry("WILLI", "Willis")
end)